#!/bin/bash

set -e

sandbox=/home/box/task8.3
paths=$(echo $PATH | sed 's/:/ /g')
for path in bin lib lib64 media mnt opt run sbin srv tmp usr ; do
	[ ! -d $sandbox/$path ] && cp -r /$path $sandbox/$path
done
for path in $paths ; do
	[ ! -d $sandbox/$path ] && mkdir -p $sandbox/$(dirname $path)
	cp -r $path $sandbox/$path
done

sudo chroot $sandbox $@

																				
